---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pdwtheme

<!-- badges: start -->
<!-- badges: end -->

The goal of pdwtheme is to ...

## Installation

And the current version from [GitHub](https://github.com/) with:

```{r, eval=F}
# install.packages("devtools")
devtools::install_github("phildwalker/pdwtheme")

# or via 
remotes::install_github("phildwalker/pdwtheme", ref = "main")
```

## Colors used

```{r corporate_swatch, echo = F}
cols <- c(red = "#d11141", green = "#00b159", blue = "#00aedb", orange = "#f37735", yellow = "#ffc425", `light grey` = "#cccccc", `dark grey` = "#8c8c8c")
n_seq <- seq_along(cols)
image(1, n_seq, t(as.matrix(n_seq)), col = cols,
          xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n",
      main = "Colors used for pdw theme")
text(0.8, n_seq, names(cols), col = "white")
text(1.2, n_seq, cols, col = "white")

```


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(pdwtheme)
library(ggplot2)

theme_set(theme_minimal())
## basic example code
```




```{r example of colors}

# Color by discrete variable using default palette
ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Species)) +
  geom_point(size = 4) +
  scale_color_pdw()

```

## Another example of different palettes 

### Using the mixed palette

```{r}
# Fill by discrete variable with different palette + remove legend (guide)
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
    geom_bar() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_pdw(palette = "mixed", guide = "none")
```

### Using the main palette

```{r}
# Fill by discrete variable with different palette + remove legend (guide)
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
    geom_bar() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_pdw(palette = "main", guide = "none")
```

